using WotBTreader.Application.Results;

namespace WotBTreader.Application.Diagnostics;

/// <summary>
/// One check result within a <see cref="DoctorReport"/>. Carries a stable ID,
/// status, summary, required flag, and optional key-value data.
/// </summary>
/// <param name="Id">Stable machine-readable check identifier (e.g. "storage.can-connect").</param>
/// <param name="Status">Outcome: "Pass", "Fail", "Warning", or "Skipped".</param>
/// <param name="Summary">Human-readable one-line result description.</param>
/// <param name="Required">True if a failing check makes the application non-functional.</param>
/// <param name="Data">Optional key-value pairs with check-specific details.</param>
public sealed record DiagnosticCheck(
    string Id,
    string Status,
    string Summary,
    bool Required,
    IReadOnlyDictionary<string, string> Data);

/// <summary>
/// Complete health report generated by <see cref="IDoctorService"/>.
/// Contains a schema version, generation timestamp, and all check results.
/// </summary>
/// <param name="SchemaVersion">Report schema version for forward compatibility.</param>
/// <param name="GeneratedAtUtc">UTC timestamp when the report was generated.</param>
/// <param name="Checks">All diagnostic checks that were run.</param>
public sealed record DoctorReport(
    string SchemaVersion,
    DateTimeOffset GeneratedAtUtc,
    IReadOnlyList<DiagnosticCheck> Checks);

/// <summary>
/// User-configurable options for creating a diagnostic bundle via
/// <see cref="IDiagnosticBundleService"/>.
/// </summary>
/// <param name="IncludeDatabase">Include a read-only copy of the SQLite database.</param>
/// <param name="IncludeSourceArtifacts">Include managed source artifact files (may be large).</param>
/// <param name="IncludeScreenshots">Include screenshot evidence if available.</param>
public sealed record DiagnosticBundleOptions(
    bool IncludeDatabase,
    bool IncludeSourceArtifacts,
    bool IncludeScreenshots);

/// <summary>Runs non-mutating environment and application health checks.</summary>
public interface IDoctorService
{
    /// <summary>Executes all diagnostic checks and returns a structured report.</summary>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>A complete doctor report with per-check status.</returns>
    ValueTask<DoctorReport> RunAsync(CancellationToken cancellationToken);
}

/// <summary>Exports redacted diagnostics; sensitive artifacts require explicit opt-in.</summary>
public interface IDiagnosticBundleService
{
    /// <summary>
    /// Creates a diagnostic bundle archive with the specified options.
    /// Returns the file path to the generated bundle on success.
    /// </summary>
    /// <param name="options">Controls which components to include.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Operation result with the bundle file path on success.</returns>
    ValueTask<OperationResult<string>> CreateAsync(
        DiagnosticBundleOptions options,
        CancellationToken cancellationToken);
}
