<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\WotBTreader.Application\WotBTreader.Application.csproj" />
    <ProjectReference Include="..\..\src\WotBTreader.CaptureLogs\WotBTreader.CaptureLogs.csproj" />
    <ProjectReference Include="..\..\src\WotBTreader.Core\WotBTreader.Core.csproj" />
    <ProjectReference Include="..\..\src\WotBTreader.GameIntegration\WotBTreader.GameIntegration.csproj" />
    <ProjectReference Include="..\..\src\WotBTreader.Replays\WotBTreader.Replays.csproj" />
    <ProjectReference Include="..\..\src\WotBTreader.Storage.Sqlite\WotBTreader.Storage.Sqlite.csproj" />
  </ItemGroup>

</Project>
