<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
    <PackageReference Include="Microsoft.Web.WebView2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WotBTreader.ApiContracts\WotBTreader.ApiContracts.csproj" />
  </ItemGroup>

</Project>
